services:
  redis:
    image: redis:latest
    container_name: chatbot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - chatbot-network

  chatbot:
    build: .
    container_name: chatbot-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - chatbot-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  chatbot-network:
    driver: bridge
